version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6 
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: Install and Make
          command: npm run cover -- --report lcovonly && cat ./coverage/lcov.info | coveralls
      - coveralls/upload