version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: Install and Make
          command: npm i mocha --save-dev | npm i chai  --save-dev | npm i istanbul --save-dev | npm i coveralls --save-dev | npm run cover -- --report lcovonly && cat ./coverage/lcov.info | coveralls
      - coveralls/upload